import type { NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from 'urql'
import ProductCard from '../components/ProductCard';
import { Product } from '../types/Product.type';

const getProducts = `
  query GetProducts($first: Int) {
    products(first: $first) {
      nodes {
        id
        title
        vendor
        description
        featuredImage {
          altText
          url
        }
        compareAtPriceRange {
          maxVariantPrice {
            amount
          }
          minVariantPrice {
            amount
          }
        }
      }
    }
  }
`;

const Home: NextPage = () => {

  const [{data}] = useQuery<{
    products: {
      nodes: Product[]
    }
  }>({
    query: getProducts,
    variables: {
      first: 100
    }
  })
  return (
    <div>
      <Head>
        <title>お試しアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-20'>
        <h1 className='text-xl font-bold text-slate-700 mb-10'>刀買ってください・・・</h1>
        <div className='grid grid-cols-6'>
        {data?.products?.nodes?.map((n) => <ProductCard key={n.id} data={n} />)}
        </div>
      </main>
    </div>
  )
}

export default Home
